{% set version = "1.48.11" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mumin
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MuMIn_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MuMIn/MuMIn_{{ version }}.tar.gz
  sha256: c1f3520694f37f7c96625c8baeb27c3af6a10baa2cad9905c94c3b6febb3fae7

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base >=4.4
    - r-insight
    - r-matrix
    - r-nlme
  run:
    - r-base >=4.4
    - r-insight
    - r-matrix
    - r-nlme

test:
  commands:
    - $R -e "library('MuMIn')"           # [not win]
    - "\"%R%\" -e \"library('MuMIn')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=MuMIn
  license: GPL-2.0-only
  summary: Tools for performing model selection and model averaging. Automated model selection through subsetting the maximum model, with optional constraints for model inclusion. Model parameter and prediction averaging based on model weights derived from information criteria (AICc and alike) or custom model weighting schemes.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - jacodela
