{% set version = "1.43.17" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mumin
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MuMIn_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MuMIn/MuMIn_{{ version }}.tar.gz
  sha256: ac6196d21dc654b64b04c39084094075482acdec3464b4f88c6748921e4787a9

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-nlme
  run:
    - r-base
    - r-matrix
    - r-nlme

test:
  commands:
    - $R -e "library('MuMIn')"           # [not win]
    - "\"%R%\" -e \"library('MuMIn')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=MuMIn
  license: GPL-2.0-only
  summary: Tools for performing model selection and model averaging. Automated model selection through subsetting the maximum model, with optional constraints for
    model inclusion. Model parameter and prediction averaging based on model weights derived from information criteria (AICc and alike) or custom model weighting
    schemes.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - jacodela

# Package: MuMIn
# Type: Package
# Title: Multi-Model Inference
# Version: 1.42.1
# Date: 2018-07-21
# Encoding: UTF-8
# Author: Kamil Barton
# Maintainer: Kamil Barton <kamil.barton@go2.pl>
# Description: Tools for performing model selection and model averaging. Automated model selection through subsetting the maximum model, with optional constraints for model inclusion. Model parameter and prediction averaging based on model weights derived from information criteria (AICc and alike) or custom model weighting schemes.
# License: GPL-2
# Depends: R (>= 3.0.0)
# Imports: graphics, methods, Matrix, stats, stats4, nlme
# Suggests: lme4 (>= 1.1.0), mgcv (>= 1.7.5), gamm4, MASS, nnet, survival (>= 2.37.5), geepack
# Enhances: aod, aods3, betareg, caper, coxme, cplm, gee, glmmML, logistf, MCMCglmm, ordinal, pscl, spdep, splm, unmarked (>= 0.12.2), geeM (>= 0.7.5)
# LazyData: yes
# ByteCompile: yes
# Repository: CRAN
# Repository/R-Forge/Project: mumin
# Repository/R-Forge/Revision: 440
# Repository/R-Forge/DateTimeStamp: 2018-07-22 18:13:45
# Date/Publication: 2018-07-23 07:40:03 UTC
# NeedsCompilation: no
# Packaged: 2018-07-22 18:30:10 UTC; rforge
